const players = [
  "Harry Kane",
  "Kylian Mbappe",
  "Karim Benzema",
  "Lionel Messi",
  "Neymar",
  "Cristiano Ronaldo",
  "Romelu Lukaku",
  "Lautaro Martinez",
  "Memphis Depay",
  "Vinicius Junior",
  "Richarlison",
  "Gabriel Jesus",
  "Alvaro Morata",
  "Kai Havertz",
  "Robert Lewandowski",
  "Raphinha",
  "Raheem Sterling",
  "Serge Gnabry",
  "Antoine Griezmann",
  "Karim Adeyemi",
  "Darwin Nunez",
  "Sequeira Joao Felix",
  "Pablo Sarabia",
  "Ferran Torres",
  "Aleksandar Mitrovic",
  "Cody Gakpo",
  "Phil Foden",
  "Dusan Vlahovic",
  "Julian Alvarez",
  "Luis Suarez",
  "Rafael Leao",
  "Ansu Fati",
  "Gareth Bale",
  "Thomas Muller",
  "Steven Bergwijn",
  "Anthony",
  "Niclas Fullkrug",
  "Gerard Moreno",
  "Bernardo Silva",
  "Kevin De Bruyne",
  "Sadio Mane",
  "Leroy Sane",
  "Bruno Fernandes",
  "Marco Asensio",
  "Jamal Musiala",
  "Michy Batshuayi",
  "Ousmane Dembele",
  "Steven Berghuis",
  "Edinson Cavani",
  "Olivier Giroud",
  "Marcus Rashford",
  "Eden Hazard",
  "Leandro Trossard",
  "Antony",
  "Breel Embolo",
  "Andre Silva",
  "Xavi Simons",
  "Daryl Dike",
  "Karl Toko Ekambi",
  "Gio Reyna",
  "Kingsley Coman",
  "Marco Reus",
  "Sofiane Boufal",
  "Federico Valverde",
  "Donyell Malen",
  "Son Heung-min",
  "Bukayo Saka",
  "Dries Mertens",
  "Luka Jovic",
  "Kasper Dolberg",
  "Dani Olmo",
  "Luuk De Jong",
  "Youssoufa Moukoko",
  "Yussuf Poulsen",
  "Christopher Nkunku",
  "Jack Grealish",
  "Keita Balde",
  "Raul Jimenez",
  "Youssef En-Nesyri",
  "Wouter Weghorst",
  "Christian Pulisic",
  "Mason Mount",
  "Dusan Tadic",
  "Andrej Kramaric",
  "Krzysztof Piatek",
  "Ilkay Gundogan",
  "Jonathan David",
  "Callum Wilson",
  "Angel Di Maria",
  "Leon Goretzka",
  "Achraf Hakimi",
  "Stephen Eustaquio",
  "Michael Estrada",
  "Martin Braithwaite",
  "Alexis Vega",
  "Hwang Hee-Chan",
  "Toni Kroos",
  "Ante Rebic",
  "Vincent Aboubakar",
  "Takumi Minamino",
  "Jonas Wind",
  "Giovanni Reyna",
  "Sardar Azmoun",
  "Ivan Perisic",
  "Luka Modric",
  "Josh Sargentbruno",
  "Christian Eriksen",
  "Haris Seferovic",
  "Cyle Larin",
  "Hakim Ziyech",
  "Andre Ayew",
  "Hirving Lozano",
  "Jordan Ayew",
  "Eric Maxim Choupo-Moting",
  "Yuya Osako",
  "Timothy Weah",
  "Ismaila Sarr",
  "Wahbi Khazri",
  "Mehdi Taremi",
  "Gyasi Zardes",
  "Mario Gavranovic",
  "Enner Valencia",
  "Xherdan Shaqiri",
  "James Maddison",
  "Paul Arriola",
  "Kamaldeen Sulemana",
  "Karim Ansarifard",
  "Almoez Ali",
  "Junior Hoilett",
  "Seifeddine Jaziri",
  "Brenden Aaronson",
  "Thomas Partey",
  "Jamie Maclaren",
  "Famara Diedhiou",
  "Jesus Ferreira",
  "Salem Al-Dawsari",
  "Saleh Al-Shehri",
  "Akram Afif",
  "Alphonso Davies",
  "Jason Cummings",
  "Iliman Ndiaye",
  "Aaron Ramsey",
  "Jewison Bennette",
  "Each Way Terms"
];

export const goalies = [
  "Alisson",
  "Thibaut Courtois",
  "Manuel Neuer",
  "Emiliano Martinez",
  "Unai Simon",
  "Hugo Lloris",
  "Jordan Pickford",
  "Diogo Costa",
  "Jasper Cillessen",
  "Rui Patricio",
  "Remko Pasveer",
  "Kasper Schmeichel",
  "Dominik Livakovic",
  "Fernando Muslera",
  "Marko Dmitrovic",
  "Wojciech Szczesny",
  "Yan Sommer",
  "Edouard Mendy",
  "Matt Turner",
  "Wayne Hennessey",
  "Milan Borjan",
  "Guillermo Ochoa",
  "Andre Onana",
  "Mathew Ryan",
  "Keylor Navas"
];

export default players;